name: Dotnet 8.x nuget build and pack
on:
  workflow_call:
    inputs:
      dotnet_build_file:
        required: true
        type: string
    secrets:
      token:
        required: true
jobs:
  build-and-pack:
    env:
        dotnet_version: 8.x
        dotnet_package_version: 8.1.${{ github.run_number }}
    runs-on: ubuntu-latest
      
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: use .NET ${{ env.dotnet_version }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.dotnet_version }}

    - name: show source
      run: dotnet nuget list source

    - name: use nuGet
      id: add-nuget-source
      run: |
        dotnet nuget add source https://nuget.pkg.github.com/transpaygo/index.json -n github -u user -p ${{ secrets.token }} --store-password-in-clear-text
        
    - name: show source
      run: dotnet nuget list source
      
    - name: restore
      run: dotnet restore ${{ inputs.dotnet_build_file }}

    - name: pack
      run: |
        dotnet pack ${{ inputs.dotnet_build_file }} \
        --no-restore \
        --configuration Release \
        --include-symbols \
        -p:PackageVersion=${{ env.dotnet_package_version }} \
        -o ${{ github.workspace }}

    - name: publish
      run: |
        dotnet nuget push ${{ github.workspace }}/*.symbols.nupkg \
        --source https://nuget.pkg.github.com/transpaygo/index.json \
        --api-key  ${{ secrets.GITHUB_TOKEN }}
