name: Dotnet 8.x nuget build and pack
on:
  workflow_call:
    inputs:
      dotnet_build_file:
        required: true
        type: string

jobs:
  build-and-pack:
    env:
        dotnet_version: 8.x
        dotnet_package_version: 8.1.${{ github.run_number }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.dotnet_version }}

    - name: Add GitHub NuGet Source
      id: add-nuget-source
      run: |
        dotnet nuget add source https://nuget.pkg.github.com/transpaygo/index.json -n github -u user -p ${{ secrets.GITHUB_TOKEN }}

    - name: list nuget
      run: dotnet nuget list source 

# add dotnet restore with nuget.org
# and custom nuget: https://nuget.pkg.github.com/transpaygo/index.json
    - name: Build and pack
# split in 2 steps dontet restore 
# dotnet pack --no-restore arg
      run: |
        dotnet pack ${{ inputs.dotnet_build_file }}  --configuration Release --include-symbols -p:PackageVersion=${{ env.dotnet_package_version }} -o ${{ github.workspace }}

    - name: Publish package
      run: |
        dotnet nuget push ${{ github.workspace }}/*.symbols.nupkg --source https://nuget.pkg.github.com/transpaygo/index.json --api-key  ${{ secrets.GITHUB_TOKEN }}
