name: Dotnet 8.x nuget build and pack
on:
  workflow_call:
    inputs:
      dotnet_build_file:
        required: true
        type: string
jobs:
  build-and-pack:
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
      dotnet_version: 8.x
      dotnet_package_version: 8.1.${{ github.run_number }}
    runs-on: ubuntu-latest
      
    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: use .NET ${{ env.dotnet_version }}
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.dotnet_version }}
        source-url: https://nuget.pkg.github.com/transpaygo/index.json
        cache: true
        cache-dependency-path: src/dataAccess/packages.lock.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: restore
      run: dotnet restore ${{ inputs.dotnet_build_file }} --locked-mode

    - name: pack
      run: |
        dotnet pack ${{ inputs.dotnet_build_file }} \
        --no-restore \
        --configuration Release \
        --include-symbols \
        -p:PackageVersion=${{ env.dotnet_package_version }} \
        -o ${{ github.workspace }}

    - name: publish
      run: |
        dotnet nuget push ${{ github.workspace }}/*.symbols.nupkg
