# .github/workflows/reusable_workflow.yaml
name: Reusable Workflow
on:
  workflow_call:
    inputs:
      dotnet_version:
        required: true
        type: string
      dotnet_package_version:
        required: true
        type: string
      dotnet_build_file:
        required: true
        type: string

jobs:
  build-and-pack:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ inputs.dotnet_version }}

    - name: Build and pack
      run: |
        dotnet pack ${{ inputs.dotnet_build_file }}  --configuration Release --include-symbols -p:PackageVersion=${{ inputs.dotnet_package_version }} -o ${{ github.workspace }}

    - name: Publish package
      run: |
        dotnet nuget push ${{ github.workspace }}/*.symbols.nupkg --source https://nuget.pkg.github.com/transpaygo/index.json --api-key  ${{ secrets.GITHUB_TOKEN }}
